---
title: "St. Louis, MO Children Blood Lead Levels"
subtitle: "Data obtained from https://github.com/slu-soc1120/STL_HEALTH_Lead"
date: "14 August 2023"
format: html
editor: visual
execute: 
  warning: false
---

```{r}
library(tidyverse)
library(janitor)
```


```{r}
stl_lead <- read_csv(here::here("data", "stl_lead.csv")) %>%
  clean_names()
```

```{r}
stl_lead_prop <- stl_lead %>%
  mutate(prop_white = (white/total_pop) * 100)
```

```{r}
stl_lead_plot <- ggplot(stl_lead_prop, aes(x = prop_white, y = pct_elevated)) +
  geom_point(alpha = 0.6, color = "darkgreen") +
  theme_linedraw() +
  labs(x = "Proportion White", y = "Percent with elevated PCT")

stl_lead_plot
```

As the proportion of white children increases, the percentage with elevated PCT levels decreases.

```{r}
ggsave(plot = stl_lead_plot, here::here("figs", "stl_lead_plot.png"), height = 5, width = 6)
```

```{r}
stl_lead_hist <- ggplot(stl_lead_prop, aes(x = pct_elevated)) +
  geom_histogram(fill = "lightblue", color = "black") +
  labs(x = "Percentage of children with elevated blood lead levels") +
  theme_linedraw()

stl_lead_hist
```

```{r}
ggsave(plot = stl_lead_hist, here::here("figs", "stl_lead_hist.jpg"), height = 5, width = 6)

```

